//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TreeModel", "FK_TreeData_TreeData", "TreeData", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(JNotes.Web.TreeData), "TreeData1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JNotes.Web.TreeData), true)]

#endregion

namespace JNotes.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TreeEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TreeEntities2 object using the connection string found in the 'TreeEntities2' section of the application configuration file.
        /// </summary>
        public TreeEntities2() : base("name=TreeEntities2", "TreeEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TreeEntities2 object.
        /// </summary>
        public TreeEntities2(string connectionString) : base(connectionString, "TreeEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TreeEntities2 object.
        /// </summary>
        public TreeEntities2(EntityConnection connection) : base(connection, "TreeEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TreeData> TreeDatas
        {
            get
            {
                if ((_TreeDatas == null))
                {
                    _TreeDatas = base.CreateObjectSet<TreeData>("TreeDatas");
                }
                return _TreeDatas;
            }
        }
        private ObjectSet<TreeData> _TreeDatas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TreeDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTreeDatas(TreeData treeData)
        {
            base.AddObject("TreeDatas", treeData);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TreeModel", Name="TreeData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TreeData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TreeData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static TreeData CreateTreeData(global::System.Guid id)
        {
            TreeData treeData = new TreeData();
            treeData.Id = id;
            return treeData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> Parent
        {
            get
            {
                return _Parent;
            }
            set
            {
                OnParentChanging(value);
                ReportPropertyChanging("Parent");
                _Parent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Parent");
                OnParentChanged();
            }
        }
        private Nullable<global::System.Guid> _Parent;
        partial void OnParentChanging(Nullable<global::System.Guid> value);
        partial void OnParentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sortorder
        {
            get
            {
                return _Sortorder;
            }
            set
            {
                OnSortorderChanging(value);
                ReportPropertyChanging("Sortorder");
                _Sortorder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sortorder");
                OnSortorderChanged();
            }
        }
        private Nullable<global::System.Int32> _Sortorder;
        partial void OnSortorderChanging(Nullable<global::System.Int32> value);
        partial void OnSortorderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isExpanded
        {
            get
            {
                return _isExpanded;
            }
            set
            {
                OnisExpandedChanging(value);
                ReportPropertyChanging("isExpanded");
                _isExpanded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isExpanded");
                OnisExpandedChanged();
            }
        }
        private Nullable<global::System.Boolean> _isExpanded;
        partial void OnisExpandedChanging(Nullable<global::System.Boolean> value);
        partial void OnisExpandedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TreeModel", "FK_TreeData_TreeData", "TreeData1")]
        public EntityCollection<TreeData> ChildNodes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TreeData>("TreeModel.FK_TreeData_TreeData", "TreeData1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TreeData>("TreeModel.FK_TreeData_TreeData", "TreeData1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TreeModel", "FK_TreeData_TreeData", "TreeData")]
        public TreeData ParentNode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TreeData>("TreeModel.FK_TreeData_TreeData", "TreeData").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TreeData>("TreeModel.FK_TreeData_TreeData", "TreeData").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TreeData> ParentNodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TreeData>("TreeModel.FK_TreeData_TreeData", "TreeData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TreeData>("TreeModel.FK_TreeData_TreeData", "TreeData", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
